### ISSUE TITLE
Failed to build from source from MSYS2 with CMake

### ISSUE THREAD

**Issue by BLumia** [juce-framework/JUCE#887]
New user from other toolkit here, tried to build it under MSYS2 MinGW64 environment but seems not be able to build. Here is the `cmake` output:

``` plain
$ cmake ../ -GNinja -DJUCE_MINGW=on
-- Configuring juceaide
-- Building juceaide
CMake Error at extras/Build/juceaide/CMakeLists.txt:86 (message):
  Failed to build juceaide
  [0/2] Re-checking globbed directories...
  [1/2] Building CXX object
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.obj

  FAILED:
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.obj

  C:\tools\msys64\mingw64\bin\c++.exe -DDEBUG=1
  -DJUCE_DISABLE_JUCE_VERSION_PRINTING=1
  -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1
  -DJUCE_MODULE_AVAILABLE_juce_build_tools=1
  -DJUCE_MODULE_AVAILABLE_juce_core=1
  -DJUCE_MODULE_AVAILABLE_juce_data_structures=1
  -DJUCE_MODULE_AVAILABLE_juce_events=1
  -DJUCE_MODULE_AVAILABLE_juce_graphics=1
  -DJUCE_MODULE_AVAILABLE_juce_gui_basics=1 -DJUCE_STANDALONE_APPLICATION=1
  -DJUCE_USE_CURL=0 -D_CONSOLE=1 -D_DEBUG=1
  -Iextras/Build/juceaide/juceaide_artefacts/JuceLibraryCode
  -I../../extras/Build -I../../modules -Wa,-mbig-obj -g -O0 -Wall -Wextra
  -Wstrict-aliasing -Wuninitialized -Wunused-parameter -Wsign-compare
  -Woverloaded-virtual -Wreorder -Wsign-conversion -Wunreachable-code
  -Wzero-as-null-pointer-constant -Wcast-align -Wno-implicit-fallthrough
  -Wno-maybe-uninitialized -Wno-missing-field-initializers
  -Wno-ignored-qualifiers -Wswitch-enum -Wredundant-decls -Wpedantic
  -Wno-strict-overflow -MD -MT
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.obj
  -MF
  extras\Build\juceaide\CMakeFiles\juceaide.dir\__\__\__\modules\juce_gui_basics\juce_gui_basics.cpp.obj.d
  -o
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_gui_basics/juce_gui_basics.cpp.obj
  -c ../../modules/juce_gui_basics/juce_gui_basics.cpp
  In file included from
  ../../modules/juce_gui_basics/juce_gui_basics.cpp:252:
  ../../modules/juce_gui_basics/native/juce_win32_Windowing.cpp:1057:32:
  warning: multi-character character constant [-Wmultichar]
   1057 |             header.bV5CSType = LCS_WINDOWS_COLOR_SPACE;
        |                                ^~~~~~~~~~~~~~~~~~~~~~~
  In file included from
  ../../modules/juce_gui_basics/juce_gui_basics.cpp:254:
  ../../modules/juce_gui_basics/native/juce_win32_FileChooser.cpp: In member
  function 'virtual HRESULT
  juce::Win32NativeFileChooser::showDialog(IFileDialog&,
  bool)::Events::OnTypeChange(IFileDialog*)':
  ../../modules/juce_gui_basics/native/juce_win32_FileChooser.cpp:235:17:
  error: 'IUnknown_GetWindow' was not declared in this scope
    235 |                 IUnknown_GetWindow (d, &hwnd);
        |                 ^~~~~~~~~~~~~~~~~~
  ninja: build stopped: subcommand failed.


-- Configuring incomplete, errors occurred!
See also "C:/Users/Gary/Sources/JUCE/build/CMakeFiles/CMakeOutput.log".
```

I'm using cmake 3.20.0 and gcc x86_64-w64-mingw32 10.2.0 from MSYS2 64-bit MinGW environment. Trying to build both current master (fbe95b0) and develop (df132fd) branch, both get the same result. I also notice there is a `JUCE_MINGW` define in source code but building with something like `cmake ../ -GNinja -D CMAKE_CXX_FLAGS=\-DJUCE_MINGW=1` also get the same result, not sure if I'm using it correctly, if not, I'd like to know how to use it correctly.

Thanks!

**Comment by McMartin** [comment]
Usage of `IUnknow_GetWindow` was introduced in https://github.com/juce-framework/JUCE/commit/45409bb4e62fa583b8e4973cdd72f479af814174, which is part of JUCE 6.0.8.
You could try building JUCE 6.0.7, you might get lucky.

**Comment by BLumia** [comment]
Thanks! 6.0.7 can build without any extra configuration. Should I leave this issue open?

**Comment by McMartin** [comment]
Yes please, since 6.0.7 builds but 6.0.8 doesn't, we're dealing with a regression that should be fixed. 
Pinging @reuk who authored https://github.com/juce-framework/JUCE/commit/45409bb4e62fa583b8e4973cdd72f479af814174.

**Comment by reuk** [comment]
Thanks for the report, I've fixed this issue in this commit: https://github.com/juce-framework/JUCE/commit/a10cc6faffcf42823c95ae6934d00200b24ebb54

In testing, it seems that MinGW isn't able to open the 'new' style of file dialog, so when building with MinGW we now only allow opening the 'old' XP-style native dialogs.

**Comment by BLumia** [comment]
Thanks for the fix! Just tested with the current develop branch HEAD (1a5fb5992) and now it can also compile without any extra configuration.
