### ISSUE TITLE
error: use of undeclared identifier 'arrayContainsPlugin'

### ISSUE THREAD

**Issue by yurivict** [juce-framework/JUCE#875]
Version 6.0.8 fails to compile with clang-10 on FreeBSD 12.2 (with compatibility patches):

```
In file included from /usr/ports/devel/juce/work/JUCE-33acd2e/modules/juce_audio_processors/juce_audio_processors.cpp:238:
/usr/ports/devel/juce/work/JUCE-33acd2e/modules/juce_audio_processors/format_types/juce_LADSPAPluginFormat.cpp:606:23: error: use of undeclared identifier 'arrayContainsPlugin'
                if (! arrayContainsPlugin (results, desc))
                      ^
1 error generated.
```

**Comment by reuk** [comment]
This function is only defined when `JUCE_LINUX` is also defined. It sounds like the `#if` at the top of `juce_audio_processors.cpp` will need patching to make this function visible when building for BSD.

Note that JUCE doesn't currently have official support for BSD.

**Comment by yurivict** [comment]
Sorry, my bad.
