### ISSUE TITLE
[Bug]: Juce 7.0.x doesn't compile with C++23 on AppleClang

### ISSUE THREAD

**Issue by lkotsonis** [juce-framework/JUCE#1350]
### Detailed steps on how to reproduce the bug

Try building e.g. the DemoRunner using the XCode project and setting the C++ standard to C++23.

### What is the expected behaviour?

That compilation of the juce libraries succeeds using C++23.

### Operating systems

macOS

### What versions of the operating systems?

Sonoma 14.3.1
XCode 15.2

### Architectures

ARM

### Stacktrace
XCode errors:
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__memory/unique_ptr.h:63:19: Invalid application of 'sizeof' to an incomplete type 'juce::AccessibilityHandler'

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__memory/unique_ptr.h:63:19: Invalid application of 'sizeof' to an incomplete type 'juce::Drawable'


```

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by lkotsonis** [comment]
I also tested this with 7.0.10.

**Comment by tarlanahad** [comment]
No solution yet?

**Comment by lkotsonis** [comment]
> No solution yet?

The commits I've seen after 7.0.10 don't seem to tackle anything related to C++23, but also I haven't tried building again using C++23 since then. Did you also get a failure @tarlanahad ?

**Comment by Anthony-Nicholls** [comment]
Thanks we're aware of the issue but we're working on JUCE 8 first. Unfortunately to fix builds for C++23 we'll need to make changes in areas that have been heavily modified in JUCE 8 which is why we haven't tackled this yet.

Sorry for any inconvenience caused and thanks for your patience.

**Comment by tarlanahad** [comment]
@lkotsonis , yes, I'm getting failure mainly because of not fully defined unique_ptr, which C++ 23 strictly requires. 

I hope you can solve this, @Anthony-Nicholls , we will be looking forward to using JUCE with C++ 23. Thanks for the prompt response.

**Comment by adamjmurray** [comment]
Not sure if this is the right issue, since it's about Apple Clang and JUCE 7, but it's kind of a duplicate...

I am using the clang++ that comes with LLVM 18 (on MacOS), which now has support for a lot of C++23 and even some C++26, but I cannot get JUCE apps to compile with C++23 or higher due to this one lingering error:

```
/opt/homebrew/opt/llvm/bin/../include/c++/v1/__memory/unique_ptr.h:64:19: error: invalid application of 'sizeof' to an incomplete type 'juce::JUCEApplicationBase::MultipleInstanceHandler'
   64 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
      |                   ^~~~~~~~~~~
```

The same error occurs with clang++/LLVM 17.

Any chance of this being resolved now that JUCE 8 has been released? Any workarounds?

Let me know if I should open a new issue specifically for JUCE 8. I'm guessing this won't be resolved in JUCE 7.

**Comment by tpoole** [comment]
Please add this as a new issue for JUCE 8 - we are not going to make any changes to JUCE 7.

We have also already fixed some other C++23 issues on the JUCE 8 `develop` branch, and this issue might have been addressed there too.

**Comment by adamjmurray** [comment]
Sounds good @tpoole . When I get a chance, I'll try the `develop` branch to see if the error is fixed already, otherwise I'll open a new issue for JUCE 8.

**Comment by adamjmurray** [comment]
I checked with the latest code in the `develop` branch and I am able to build JUCE projects with C++ 23. Everything appears to work fine, so no issues to report. I guess it will work in the `master` branch when JUCE 8.0.2 ships.

**Comment by tpoole** [comment]
Thank you @adamjmurray
