### ISSUE TITLE
[Bug]: 'exchange' is not a member of 'std' (GCC 12)

### ISSUE THREAD

**Issue by jpcima** [juce-framework/JUCE#1068]
### Detailed steps on how to reproduce the bug

Build on Linux with GCC 12.1.0.

The error arises from `juce_ComponentPeer.h`, which should include `<utility>` for `std::exchange` but it doesn't.

### What is the expected behaviour?

It compiles.

### Operating systems

Linux

### What versions of the operating systems?

Arch current

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jpcima** [comment]
A mistake, sorry
